### ISSUE TITLE
Citizens bug

### ISSUE THREAD

**Issue by SmellyOG** [Samsuik/Sakura#2] opened 2023-11-15 12:01 UTC
With sakura spigot https://prnt.sc/6DQ772RMfVPI
without u spigot https://prnt.sc/fbIGrlPmoAqG

**Comment by SmellyOG** [comment] 2023-11-15 12:04
look irongolem

**Comment by Samsuik** [comment] 2023-11-15 13:39
I was not able to reproduce this locally with citizens but this should be fixed in the latest release with 8fe647d02b07b367a66a3e4b37a5288500cb2322. I will leave this issue open because I am not sure my changes will fix the issue.

**Comment by SmellyOG** [comment] 2023-11-16 12:39
close the insuee, its citizens

**Closed as completed** 2023-11-16 13:20 UTC
